services:
  elasticmq:
    image: softwaremill/elasticmq-native:1.5.0
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./infra/docker/elasticmq/custom-sqs.conf:/opt/elasticmq.conf
