package com.pg.worker.global.logging

object WorkerLogPayloadKeys {
    const val PHASE = "phase"
    const val REASON = "reason"
    const val EVENT_ID = "eventId"
    const val MESSAGE_ID = "messageId"
    const val TRACE_ID = "traceId"
    const val MERCHANT_ID = "merchantId"
    const val QUEUE_URL = "targetQueueName"
    const val SOURCE_QUEUE_URL = "sourceQueueName"
    const val DLQ_URL = "dlqUrl"
    const val RETRY_COUNT = "retryCount"
    const val NEXT_RETRY_AT = "nextRetryAt"
    const val RAW_ID = "rawId"
    const val TARGET_STATUS = "targetStatus"
    const val SQS_MESSAGE_ID = "sqsMessageId"
    const val SCHEMA_VERSION = "schemaVersion"
    const val EVENT_TYPE = "eventType"
    const val OCCURRED_AT = "occurredAt"
    const val TRANSACTION_TYPE = "transactionType"
    const val STATUS_LABEL = "statusLabel"
    const val ERROR = "error"
    const val FAILURE_REASON = "failureReason"
    const val RECEIVE_COUNT = "receiveCount"
    const val EVENT_BODY_SIZE = "eventBodySize"
    const val RECEIVED_COUNT = "receivedCount"
    const val VISIBILITY_SEC = "visibilitySec"
    const val WAIT_SEC = "waitSec"
    const val POLL_MAX = "pollMax"
    const val HTTP_STATUS = "httpStatus"
    const val ENDPOINT_COUNT = "endpointCount"
}
